import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { BrandMark } from '../components/BrandMark';
import { api, API_BASE_URL } from '../services/api';
import { authStorage } from '../services/authStorage';
import { colors } from '../theme';
import type { Session } from '../types';

export function LoginScreen({ onAuthenticated }: { onAuthenticated: (session: Session) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async () => { if (!email.trim() || !password) return setError('Enter your email and password.'); setBusy(true); setError(''); try { const session = await api.login(email, password); await authStorage.write(session); onAuthenticated(session); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Login failed'); } finally { setBusy(false); } };
  return <LinearGradient colors={['#111A27', colors.bg, '#050608']} style={styles.fill}><SafeAreaView style={styles.fill}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.content}><View><BrandMark /><Text style={styles.title}>Welcome back.</Text><Text style={styles.subtitle}>Real people. Real worlds. Pick up where you left off.</Text></View><View style={styles.form}><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" onChangeText={setEmail} placeholder="Email" placeholderTextColor={colors.faint} style={styles.input} value={email} /><TextInput autoComplete="password" onChangeText={setPassword} onSubmitEditing={submit} placeholder="Password" placeholderTextColor={colors.faint} secureTextEntry style={styles.input} value={password} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={busy} onPress={submit} style={({ pressed }) => [styles.button, pressed && styles.pressed, busy && styles.disabled]}>{busy ? <ActivityIndicator color={colors.bg} /> : <Text style={styles.buttonText}>Enter @seen</Text>}</Pressable><Text style={styles.endpoint}>API: {API_BASE_URL}</Text></View></KeyboardAvoidingView></SafeAreaView></LinearGradient>;
}
const styles = StyleSheet.create({ fill: { flex: 1 }, content: { flex: 1, justifyContent: 'space-between', paddingHorizontal: 24, paddingTop: 76, paddingBottom: 38 }, title: { marginTop: 48, color: colors.text, fontSize: 40, fontWeight: '900', letterSpacing: -1.5 }, subtitle: { marginTop: 12, maxWidth: 310, color: colors.muted, fontSize: 15, lineHeight: 23 }, form: { gap: 12 }, input: { height: 56, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: 'rgba(24,29,37,.86)', color: colors.text, paddingHorizontal: 17, fontSize: 15 }, button: { height: 56, marginTop: 4, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blue }, buttonText: { color: colors.bg, fontWeight: '900', fontSize: 16 }, pressed: { transform: [{ scale: .985 }] }, disabled: { opacity: .55 }, error: { color: colors.danger, fontSize: 12 }, endpoint: { color: colors.faint, fontSize: 9, textAlign: 'center', marginTop: 4 } });
