import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../theme';
import { resolveMediaUrl } from '../services/api';
import type { MainTab } from '../types';

const items = [{ key: 'seen', label: 'Seen', icon: 'eye-outline' }, { key: 'discover', label: 'Discover', icon: null }, { key: 'wall', label: 'Wall', icon: 'easel-outline' }, { key: 'messages', label: 'Messages', icon: 'chatbubble-outline' }, { key: 'profile', label: 'Profile', icon: 'person-circle-outline' }] as const;
function DiscoverIcon({ color }: { color: string }) { return <View style={styles.discoverIcon}><View style={[styles.discoverRect, styles.discoverFirst, { borderColor: color }]} /><View style={[styles.discoverRect, styles.discoverSecond, { borderColor: color }]} /></View>; }
export function BottomNav({ active, avatar, name, onSelect }: { active: MainTab; avatar?: string; name?: string; onSelect: (key: MainTab) => void }) { const avatarUrl = resolveMediaUrl(avatar); return <View style={styles.nav}>{items.map((item) => { const selected = active === item.key; const color = selected ? colors.blue : colors.faint; return <Pressable accessibilityLabel={item.label} accessibilityRole="button" hitSlop={8} key={item.key} onPress={() => onSelect(item.key)} style={styles.item}>{item.key === 'profile' ? <View style={[styles.avatarShell, selected && styles.avatarActive]}>{avatarUrl ? <Image source={{ uri: avatarUrl }} style={styles.avatar} /> : <View style={styles.avatarFallback}><Text style={styles.avatarLetter}>{name?.trim()?.[0]?.toUpperCase() || '?'}</Text></View>}</View> : item.icon ? <Ionicons name={selected ? item.icon.replace('-outline', '') as keyof typeof Ionicons.glyphMap : item.icon} size={24} color={color} /> : <DiscoverIcon color={color} />}<View style={[styles.dot, selected && styles.dotActive]} /></Pressable>; })}</View>; }
const styles = StyleSheet.create({ nav: { height: 64, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-around', borderTopColor: colors.line, borderTopWidth: 1, backgroundColor: '#0D1014', paddingTop: 12 }, item: { width: 64, height: 42, alignItems: 'center', justifyContent: 'flex-start' }, dot: { width: 3, height: 3, borderRadius: 2, marginTop: 5, backgroundColor: 'transparent' }, dotActive: { backgroundColor: colors.blue }, discoverIcon: { width: 25, height: 25 }, discoverRect: { position: 'absolute', width: 10, height: 16, borderWidth: 1.8, borderRadius: 3 }, discoverFirst: { left: 3, top: 1 }, discoverSecond: { right: 3, bottom: 1 }, avatarShell: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, avatarActive: { borderWidth: 1.5, borderColor: colors.blue }, avatar: { width: 26, height: 26, borderRadius: 13, borderWidth: 1, borderColor: 'rgba(255,255,255,.35)' }, avatarFallback: { width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,.22)', backgroundColor: colors.surface2 }, avatarLetter: { color: colors.blue, fontSize: 10, fontWeight: '900' } });
