import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { api } from '../services/api';
import { colors } from '../theme';
import { StoryComposer } from './StoryComposer';

type Kind = 'seen' | 'story' | 'note';
type Asset = { uri: string; name: string; type: string };
const choices: { kind: Kind; icon: keyof typeof Ionicons.glyphMap; title: string; detail: string }[] = [
  { kind: 'seen', icon: 'eye-outline', title: 'Create a Seen', detail: 'A cover and chapter people can walk through' },
  { kind: 'story', icon: 'add-circle-outline', title: 'Add to Story', detail: 'Share a photo or video for 24 hours' },
  { kind: 'note', icon: 'create-outline', title: 'Write a Note', detail: 'Share what is happening right now' },
];
const noteContexts = ['RIGHT_NOW', 'COFFEE', 'PLACE', 'TRAVEL', 'FITNESS'];

export function CreateContentSheet({ accessToken, visible, onClose, onCreated }: { accessToken: string; visible: boolean; onClose: () => void; onCreated: () => void }) {
  const [kind, setKind] = useState<Kind | null>(null); const [asset, setAsset] = useState<Asset | null>(null); const [title, setTitle] = useState(''); const [summary, setSummary] = useState(''); const [chapterTitle, setChapterTitle] = useState('Chapter 1'); const [chapter, setChapter] = useState(''); const [caption, setCaption] = useState(''); const [note, setNote] = useState(''); const [location, setLocation] = useState(''); const [context, setContext] = useState('RIGHT_NOW'); const [category, setCategory] = useState('Lifestyle'); const [categories, setCategories] = useState(['Places', 'Moving', 'Business', 'Growth', 'Lifestyle']); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (visible) api.listSeenCategories(accessToken).then((data) => setCategories(data.categories.map((item) => item.name))).catch(() => undefined); }, [accessToken, visible]);
  const reset = () => { setKind(null); setAsset(null); setTitle(''); setSummary(''); setChapterTitle('Chapter 1'); setChapter(''); setCaption(''); setNote(''); setLocation(''); setContext('RIGHT_NOW'); setError(''); };
  const close = () => { if (!busy) { reset(); onClose(); } };
  if (visible && kind === 'story') return <Modal animationType="fade" onRequestClose={() => setKind(null)} visible><StoryComposer accessToken={accessToken} onBack={() => setKind(null)} onDone={() => { reset(); onClose(); onCreated(); }} /></Modal>;
  const pick = async (allowVideo: boolean) => { setError(''); const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return setError('Photo library permission is required'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: allowVideo ? ['images', 'videos'] : ['images'], quality: 0.85, allowsEditing: !allowVideo }); if (!result.canceled) { const chosen = result.assets[0]; setAsset({ uri: chosen.uri, name: chosen.fileName || `${kind || 'upload'}-${Date.now()}.${chosen.type === 'video' ? 'mp4' : 'jpg'}`, type: chosen.mimeType || (chosen.type === 'video' ? 'video/mp4' : 'image/jpeg') }); } };
  const publish = async () => {
    setError('');
    if (kind === 'seen' && (!title.trim() || !summary.trim() || !chapterTitle.trim() || !chapter.trim() || !asset)) return setError('Add a cover, title, summary, and first chapter');
    if (kind === 'note' && !note.trim()) return setError('Write something for your Note');
    setBusy(true);
    try {
      if (kind === 'seen' && asset) { const draft = (await api.createSeenDraft({ title: title.trim(), summary: summary.trim(), category }, accessToken)).publication; const cover = await api.uploadSeenCover(draft.id, asset, draft.statusVersion, accessToken); await api.addSeenChapter(draft.id, chapterTitle.trim(), chapter.trim(), cover.publication.statusVersion, accessToken); await api.submitSeen(draft.id, cover.publication.statusVersion + 1, accessToken); }
      if (kind === 'note') await api.createNote(note.trim(), context, location.trim(), asset, accessToken);
      reset(); onClose(); onCreated();
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not publish'); } finally { setBusy(false); }
  };
  return <Modal animationType="slide" onRequestClose={close} transparent visible={visible}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.overlay}><Pressable onPress={close} style={StyleSheet.absoluteFill} /><View style={[styles.sheet, kind && styles.editor]}><View style={styles.handle} />{!kind ? <><Text style={styles.heading}>Create</Text><Text style={styles.subheading}>Share something real with your people.</Text>{choices.map((item) => <Pressable key={item.kind} onPress={() => setKind(item.kind)} style={styles.option}><View style={styles.optionIcon}><Ionicons color={colors.blue} name={item.icon} size={23} /></View><View style={styles.optionCopy}><Text style={styles.optionTitle}>{item.title}</Text><Text style={styles.optionDetail}>{item.detail}</Text></View><Ionicons color={colors.faint} name="chevron-forward" size={19} /></Pressable>)}</> : <ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={styles.editorHead}><Pressable onPress={() => { setKind(null); setError(''); }}><Ionicons color={colors.text} name="chevron-back" size={25} /></Pressable><Text style={styles.editorTitle}>{kind === 'seen' ? 'New Seen' : kind === 'story' ? 'New Story' : 'New Note'}</Text><Pressable disabled={busy} onPress={publish}><Text style={styles.publish}>{busy ? 'Publishing…' : 'Publish'}</Text></Pressable></View>
        {asset ? <View style={styles.preview}><Image resizeMode="cover" source={{ uri: asset.uri }} style={StyleSheet.absoluteFill} /><Pressable onPress={() => setAsset(null)} style={styles.remove}><Ionicons color="#fff" name="close" size={18} /></Pressable></View> : null}
        {kind === 'seen' ? <><PickButton label={asset ? 'Change cover' : 'Choose cover photo'} onPress={() => pick(false)} /><Field maxLength={120} onChange={setTitle} placeholder="Seen title" value={title} /><Field maxLength={300} multiline onChange={setSummary} placeholder="What is this Seen about?" value={summary} /><Text style={styles.label}>CATEGORY</Text><View style={styles.chips}>{categories.map((item) => <Chip active={category === item} key={item} label={item} onPress={() => setCategory(item)} />)}</View><Text style={styles.section}>First chapter</Text><Field maxLength={120} onChange={setChapterTitle} placeholder="Chapter title" value={chapterTitle} /><Field maxLength={2000} multiline onChange={setChapter} placeholder="Tell the story…" value={chapter} /></> : null}
        {kind === 'story' ? <><PickButton label={asset ? 'Choose different media' : 'Choose photo or video'} onPress={() => pick(true)} /><Field maxLength={300} multiline onChange={setCaption} placeholder="Add a caption…" value={caption} /><Text style={styles.hint}>Visible to everyone for 24 hours · reactions and replies enabled</Text></> : null}
        {kind === 'note' ? <><Field maxLength={1200} multiline onChange={setNote} placeholder="What’s happening?" value={note} /><PickButton label={asset ? 'Change optional photo' : 'Add optional photo'} onPress={() => pick(false)} /><Text style={styles.label}>CONTEXT</Text><View style={styles.chips}>{noteContexts.map((item) => <Chip active={context === item} key={item} label={item.replace('_', ' ')} onPress={() => setContext(item)} />)}</View><Field maxLength={120} onChange={setLocation} placeholder="Location (optional)" value={location} /></> : null}
        {error ? <Text style={styles.error}>{error}</Text> : null}{busy ? <ActivityIndicator color={colors.blue} style={styles.busy} /> : null}
      </ScrollView>}</View></KeyboardAvoidingView></Modal>;
}
function Field({ value, onChange, placeholder, multiline = false, maxLength }: { value: string; onChange: (value: string) => void; placeholder: string; multiline?: boolean; maxLength: number }) { return <TextInput maxLength={maxLength} multiline={multiline} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={colors.faint} style={[styles.input, multiline && styles.multiline]} value={value} />; }
function PickButton({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.pick}><Ionicons color={colors.blue} name="image-outline" size={20} /><Text style={styles.pickText}>{label}</Text></Pressable>; }
function Chip({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.chip, active && styles.chipActive]}><Text style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.62)' }, sheet: { backgroundColor: '#1C212B', borderTopLeftRadius: 22, borderTopRightRadius: 22, paddingHorizontal: 20, paddingBottom: Platform.OS === 'ios' ? 34 : 22 }, editor: { height: '88%' }, handle: { width: 38, height: 4, borderRadius: 3, backgroundColor: 'rgba(255,255,255,.28)', alignSelf: 'center', marginVertical: 10 }, heading: { color: colors.text, fontSize: 24, fontWeight: '900' }, subheading: { color: colors.muted, fontSize: 13, marginTop: 4, marginBottom: 12 }, option: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.line, gap: 13 }, optionIcon: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.surface2, alignItems: 'center', justifyContent: 'center' }, optionCopy: { flex: 1 }, optionTitle: { color: colors.text, fontWeight: '800', fontSize: 15 }, optionDetail: { color: colors.faint, fontSize: 11, marginTop: 3 }, editorHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 9 }, editorTitle: { color: colors.text, fontSize: 19, fontWeight: '900' }, publish: { color: colors.blue, fontSize: 14, fontWeight: '900' }, preview: { height: 190, borderRadius: 17, overflow: 'hidden', marginVertical: 12, backgroundColor: colors.surface }, remove: { position: 'absolute', right: 9, top: 9, width: 30, height: 30, borderRadius: 15, backgroundColor: 'rgba(0,0,0,.65)', alignItems: 'center', justifyContent: 'center' }, input: { color: colors.text, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 14, minHeight: 48, paddingHorizontal: 14, paddingVertical: 12, marginTop: 12 }, multiline: { minHeight: 96, textAlignVertical: 'top' }, pick: { height: 48, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(156,203,255,.22)', backgroundColor: 'rgba(156,203,255,.06)', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 12 }, pickText: { color: colors.blue, fontWeight: '800' }, label: { color: colors.faint, fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginTop: 18, marginBottom: 8 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, chip: { borderWidth: 1, borderColor: colors.line, borderRadius: 99, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: colors.surface }, chipActive: { borderColor: colors.blue, backgroundColor: 'rgba(156,203,255,.12)' }, chipText: { color: colors.muted, fontSize: 11, fontWeight: '700' }, chipTextActive: { color: colors.blue }, section: { color: colors.text, fontSize: 17, fontWeight: '900', marginTop: 22 }, hint: { color: colors.faint, fontSize: 11, lineHeight: 17, marginTop: 12 }, error: { color: colors.danger, fontSize: 12, textAlign: 'center', marginVertical: 14 }, busy: { marginVertical: 10 } });
