import { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, KeyboardAvoidingView, Modal, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../services/api';
import { colors } from '../theme';
import type { Engagement } from '../types';

export const reactions = [
  { key: 'LIKE', icon: '🤝', label: 'Support' }, { key: 'LOVE', icon: '❤️', label: 'Love' },
  { key: 'FIRE', icon: '🔥', label: 'Fire' }, { key: 'CLAP', icon: '👏', label: 'Clap' },
  { key: 'LAUGH', icon: '😂', label: 'Laugh' }, { key: 'SEE_YOU', icon: '👁️', label: 'I see you' },
  { key: 'SAD', icon: '🥲', label: 'Feel you' }, { key: 'PHONE', icon: '📱', label: 'Call me' },
  { key: 'STRONG', icon: '💪', label: 'Strong' }, { key: 'PRAY', icon: '🙏', label: 'Respect' },
];

type Props = { accessToken: string; engagement: Engagement; id: string; mode: 'comments' | 'reactions' | null; onClose: () => void; onUpdate: (engagement: Engagement) => void };

export function EngagementSheet({ accessToken, engagement, id, mode, onClose, onUpdate }: Props) {
  const [comment, setComment] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (mode !== 'comments') return; setLoading(true); setError(''); api.getSeenEngagement(id, accessToken).then(({ engagement: next }) => onUpdate(next)).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load comments')).finally(() => setLoading(false)); }, [accessToken, id, mode]);
  const chooseReaction = async (key: string) => { if (busy) return; setBusy(true); setError(''); try { const result = engagement.viewerReaction === key ? await api.removeSeenReaction(id, accessToken) : await api.reactToSeen(id, key, accessToken); onUpdate(result.engagement); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not react'); } finally { setBusy(false); } };
  const postComment = async () => { const value = comment.trim(); if (!value || busy) return; setBusy(true); setError(''); try { const result = await api.commentOnSeen(id, value, accessToken); onUpdate(result.engagement); setComment(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not comment'); } finally { setBusy(false); } };
  return <Modal animationType="slide" onRequestClose={onClose} presentationStyle="pageSheet" transparent visible={mode !== null}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.layer}><Pressable onPress={onClose} style={styles.scrim} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.heading}><Text style={styles.title}>{mode === 'reactions' ? 'Make it yours' : 'Comments'}</Text><Pressable onPress={onClose}><Ionicons name="close" color={colors.muted} size={24} /></Pressable></View>{error ? <Text style={styles.error}>{error}</Text> : null}{mode === 'reactions' ? <View style={styles.reactionGrid}>{reactions.map((reaction) => { const selected = engagement.viewerReaction === reaction.key; return <Pressable disabled={busy} key={reaction.key} onPress={() => chooseReaction(reaction.key)} style={[styles.reaction, selected && styles.selected]}><Text style={styles.emoji}>{reaction.icon}</Text><Text style={styles.reactionLabel}>{reaction.label}</Text><Text style={styles.count}>{engagement.reactionBreakdown?.[reaction.key] || ''}</Text></Pressable>; })}</View> : <><View style={styles.composer}><TextInput maxLength={500} multiline onChangeText={setComment} placeholder="Add a comment..." placeholderTextColor={colors.faint} style={styles.input} value={comment} /><Pressable disabled={!comment.trim() || busy} onPress={postComment} style={styles.send}>{busy ? <ActivityIndicator color={colors.bg} size="small" /> : <Ionicons name="arrow-up" color={colors.bg} size={19} />}</Pressable></View>{loading ? <ActivityIndicator color={colors.blue} style={styles.loader} /> : <FlatList contentContainerStyle={styles.commentList} data={engagement.comments || []} keyExtractor={(item) => item.id} ListEmptyComponent={<Text style={styles.empty}>Be the first to comment.</Text>} renderItem={({ item }) => <View style={styles.comment}><View style={styles.commentAvatar}><Text>{item.author?.name?.[0] || '?'}</Text></View><View style={styles.commentCopy}><Text style={styles.commentAuthor}>{item.author?.name || item.author?.username || 'Fan'}</Text><Text style={styles.commentText}>{item.text}</Text></View></View>} />}</>}</View></KeyboardAvoidingView></Modal>;
}

const styles = StyleSheet.create({ layer: { flex: 1, justifyContent: 'flex-end' }, scrim: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(0,0,0,.65)' }, sheet: { height: '72%', backgroundColor: '#1C212B', borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 18, paddingBottom: 24 }, handle: { alignSelf: 'center', width: 34, height: 4, marginVertical: 9, borderRadius: 2, backgroundColor: 'rgba(255,255,255,.28)' }, heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10 }, title: { color: colors.text, fontSize: 20, fontWeight: '900' }, error: { color: colors.danger, fontSize: 12, marginBottom: 8 }, reactionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, paddingTop: 10 }, reaction: { width: '30.5%', minHeight: 91, borderWidth: 1, borderColor: colors.line, borderRadius: 16, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', padding: 7 }, selected: { borderColor: colors.blue, backgroundColor: 'rgba(156,203,255,.12)' }, emoji: { fontSize: 26 }, reactionLabel: { color: colors.muted, fontSize: 10, fontWeight: '700', marginTop: 5 }, count: { color: colors.blue, fontSize: 9, marginTop: 2 }, composer: { flexDirection: 'row', alignItems: 'flex-end', gap: 9, marginBottom: 12 }, input: { flex: 1, minHeight: 46, maxHeight: 100, borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: colors.surface, color: colors.text, paddingHorizontal: 14, paddingVertical: 12 }, send: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blue }, loader: { marginTop: 30 }, commentList: { paddingBottom: 24 }, empty: { textAlign: 'center', color: colors.faint, marginTop: 35 }, comment: { flexDirection: 'row', gap: 10, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.line }, commentAvatar: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blue }, commentCopy: { flex: 1 }, commentAuthor: { color: colors.text, fontSize: 12, fontWeight: '800' }, commentText: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 3 } });
