import { useState } from 'react';
import { ActivityIndicator, Dimensions, Image, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { api } from '../services/api';
import { colors } from '../theme';

type Asset = { uri: string; name: string; type: string };
const palette = ['#FFFFFF', '#D6EAFF', '#9CCBFF', '#0A0C0F', '#6ECF97', '#F17878'];

export function StoryComposer({ accessToken, onBack, onDone }: { accessToken: string; onBack: () => void; onDone: () => void }) {
  const [asset, setAsset] = useState<Asset | null>(null); const [text, setText] = useState(''); const [color, setColor] = useState('#D6EAFF'); const [textStyle, setTextStyle] = useState(0); const [size, setSize] = useState(26); const [position, setPosition] = useState({ x: 50, y: 42 }); const [rotation, setRotation] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [hint, setHint] = useState(true);
  const pick = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return setError('Photo library permission is required'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images', 'videos'], quality: 0.9 }); if (!result.canceled) { const chosen = result.assets[0]; setAsset({ uri: chosen.uri, name: chosen.fileName || `story-${Date.now()}.${chosen.type === 'video' ? 'mp4' : 'jpg'}`, type: chosen.mimeType || (chosen.type === 'video' ? 'video/mp4' : 'image/jpeg') }); } };
  const share = async () => { if (!asset) return setError('Choose a photo or video first'); setBusy(true); setError(''); try { await api.createStory(asset, text.trim(), { prototypeComposer: true, transform: { scale: 1, translateX: 0, translateY: 0, rotation }, textOverlays: text.trim() ? [{ id: `mobile-${Date.now()}`, color, fontSize: size, style: textStyle, fontWeight: textStyle === 1 || textStyle === 2 ? 800 : 650, background: textStyle === 2 ? 'solid' : '', text: text.trim(), x: position.x, y: position.y }] : [], stickers: [], drawing: [] }, accessToken); onDone(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Story upload failed'); } finally { setBusy(false); } };
  const textAppearance = textStyle === 2 ? { backgroundColor: color, color: color === '#0A0C0F' ? '#fff' : '#0A0C0F', paddingHorizontal: 14, paddingVertical: 7, borderRadius: 12 } : { color, fontWeight: textStyle === 1 ? '900' as const : '700' as const, fontStyle: textStyle === 3 ? 'italic' as const : 'normal' as const, fontFamily: textStyle === 4 ? 'monospace' : undefined };
  return <View style={styles.stage}>
    {asset && !asset.type.startsWith('video/') ? <Image resizeMode="cover" source={{ uri: asset.uri }} style={[StyleSheet.absoluteFill, { transform: [{ rotate: `${rotation}deg` }, { scale: rotation % 180 ? 1.45 : 1 }] }]} /> : <View style={[StyleSheet.absoluteFill, styles.fallback]}>{asset?.type.startsWith('video/') ? <><Ionicons color="#fff" name="videocam" size={44} /><Text style={styles.videoName}>{asset.name}</Text></> : <Text style={styles.empty}>Choose a photo or video</Text>}</View>}
    <View pointerEvents="none" style={styles.shade} />
    <View style={styles.top}><Pressable accessibilityLabel="Close Story editor" onPress={onBack} style={styles.round}><Ionicons color="#fff" name="close" size={25} /></Pressable><View style={styles.topRight}><Pressable accessibilityLabel="Choose media" onPress={pick} style={styles.round}><Ionicons color="#fff" name="image" size={18} /></Pressable><Pressable accessibilityLabel="Rotate media" onPress={() => setRotation((value) => (value + 90) % 360)} style={styles.round}><Ionicons color="#fff" name="refresh" size={18} /></Pressable></View></View>
    {hint ? <Pressable onPress={() => setHint(false)} style={styles.hint}><Text style={styles.hintText}>Tap to write · drag the text  ×</Text></Pressable> : null}
    {text.trim() ? <View onMoveShouldSetResponder={() => true} onResponderMove={(event) => { const { width, height } = Dimensions.get('window'); setPosition({ x: Math.min(95, Math.max(5, event.nativeEvent.pageX / width * 100)), y: Math.min(85, Math.max(8, event.nativeEvent.pageY / height * 100)) }); }} onStartShouldSetResponder={() => true} style={[styles.overlayTextWrap, { left: `${position.x}%`, top: `${position.y}%` }]}><Text style={[styles.overlayText, { fontSize: size }, textAppearance]}>{text}</Text></View> : null}
    <Pressable onPress={pick} style={styles.thumb}>{asset && !asset.type.startsWith('video/') ? <Image source={{ uri: asset.uri }} style={StyleSheet.absoluteFill} /> : <Ionicons color="#fff" name="images-outline" size={22} />}</Pressable>
    <View style={styles.controls}><View style={styles.controlRow}><Pressable onPress={() => setTextStyle((value) => (value + 1) % 5)} style={[styles.aa, textStyle === 2 && { backgroundColor: color }]}><Text style={[styles.aaText, textStyle === 2 && { color: color === '#0A0C0F' ? '#fff' : '#0A0C0F' }]}>Aa</Text></Pressable><Pressable onPress={() => setColor((value) => palette[(palette.indexOf(value) + 1) % palette.length])} style={styles.colorRing}><View style={[styles.colorDot, { backgroundColor: color }]} /></Pressable><Pressable onPress={() => setSize((value) => Math.max(16, value - 3))} style={styles.sizeButton}><Text style={styles.sizeText}>−</Text></Pressable><Pressable onPress={() => setSize((value) => Math.min(44, value + 3))} style={styles.sizeButton}><Text style={styles.sizeText}>+</Text></Pressable><TextInput maxLength={300} onChangeText={setText} placeholder="Say it…" placeholderTextColor="rgba(255,255,255,.55)" style={styles.input} value={text} /><Pressable disabled={busy} onPress={share} style={styles.share}>{busy ? <ActivityIndicator color="#07101A" size="small" /> : <Text style={styles.shareText}>Share</Text>}</Pressable></View>{error ? <Text style={styles.error}>{error}</Text> : null}</View>
  </View>;
}

const styles = StyleSheet.create({ stage: { flex: 1, backgroundColor: '#080A0D', overflow: 'hidden' }, fallback: { backgroundColor: '#111722', alignItems: 'center', justifyContent: 'center', gap: 10 }, empty: { color: colors.muted, fontWeight: '700' }, videoName: { color: colors.muted, fontSize: 12, maxWidth: '70%' }, shade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'transparent', borderTopWidth: 110, borderBottomWidth: 150, borderColor: 'rgba(0,0,0,.28)' }, top: { position: 'absolute', left: 18, right: 18, top: Platform.OS === 'ios' ? 52 : 22, flexDirection: 'row', justifyContent: 'space-between' }, topRight: { flexDirection: 'row', gap: 9 }, round: { width: 38, height: 38, borderRadius: 20, backgroundColor: 'rgba(8,10,14,.58)', alignItems: 'center', justifyContent: 'center' }, hint: { position: 'absolute', alignSelf: 'center', top: 108, backgroundColor: 'rgba(10,13,18,.52)', borderRadius: 99, paddingHorizontal: 10, paddingVertical: 5 }, hintText: { color: 'rgba(255,255,255,.62)', fontSize: 9 }, overlayTextWrap: { position: 'absolute', transform: [{ translateX: -100 }, { translateY: -30 }], maxWidth: '82%' }, overlayText: { color: '#fff', textAlign: 'center', textShadowColor: 'rgba(0,0,0,.7)', textShadowRadius: 10, textShadowOffset: { width: 0, height: 2 } }, thumb: { position: 'absolute', left: 18, bottom: 92, width: 42, height: 54, borderRadius: 9, overflow: 'hidden', borderWidth: 1.5, borderColor: 'rgba(255,255,255,.7)', backgroundColor: 'rgba(0,0,0,.55)', alignItems: 'center', justifyContent: 'center' }, controls: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 14, paddingTop: 22, paddingBottom: Platform.OS === 'ios' ? 30 : 16, backgroundColor: 'rgba(6,8,11,.72)' }, controlRow: { flexDirection: 'row', alignItems: 'center', gap: 7 }, aa: { width: 38, height: 38, borderRadius: 20, backgroundColor: 'rgba(255,255,255,.12)', alignItems: 'center', justifyContent: 'center' }, aaText: { color: '#fff', fontWeight: '900', fontSize: 13 }, colorRing: { width: 31, height: 31, borderRadius: 16, borderWidth: 3, borderColor: colors.blue, padding: 2 }, colorDot: { flex: 1, borderRadius: 12, borderWidth: 1, borderColor: '#101318' }, sizeButton: { width: 22, height: 38, alignItems: 'center', justifyContent: 'center' }, sizeText: { color: colors.muted, fontSize: 18 }, input: { flex: 1, minWidth: 55, height: 40, borderRadius: 21, paddingHorizontal: 13, backgroundColor: 'rgba(10,13,18,.78)', color: '#fff', fontSize: 12 }, share: { height: 40, borderRadius: 21, paddingHorizontal: 15, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center' }, shareText: { color: '#07101A', fontSize: 12, fontWeight: '900' }, error: { color: colors.danger, fontSize: 10, textAlign: 'center', marginTop: 7 } });
